name: 🚀 Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 🔐 Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 31.56.146.19 >> ~/.ssh/known_hosts

    - name: 🚀 Deploy to server
      run: |
        ssh -i ~/.ssh/id_ed25519 root@31.56.146.19 << 'EOF'
          cd /var/www/blog
          git pull origin main

          # ✅ Fix permissions
          chown -R www-data:www-data storage
          chown -R www-data:www-data bootstrap/cache

          # 📦 Install dependencies
          composer install --no-interaction --prefer-dist --optimize-autoloader

          # 🛠️ Run migrations
          php artisan migrate --force
          php artisan db:seed
          # 🧰 Build frontend
          npm install
          npm run build

          # 🔧 Laravel caches
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
        EOF
